// Mocks generated by Mockito 5.4.5 from annotations
// in games_deal_tracking/test/viewModels/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:games_deal_tracking/data/model/game_deal_model.dart' as _i5;
import 'package:games_deal_tracking/data/repositories/deals_remote_data_repo_impl.dart'
    as _i4;
import 'package:games_deal_tracking/data/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchData() => (super.noSuchMethod(
        Invocation.method(
          #fetchData,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchDataByTitle(String? title) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDataByTitle,
          [title],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [DealsRemoteDataRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockDealsRemoteDataRepoImpl extends _i1.Mock
    implements _i4.DealsRemoteDataRepoImpl {
  MockDealsRemoteDataRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.ApiService);

  @override
  _i3.Future<List<_i5.GameDealModel>> fetchDeals() => (super.noSuchMethod(
        Invocation.method(
          #fetchDeals,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.GameDealModel>>.value(<_i5.GameDealModel>[]),
      ) as _i3.Future<List<_i5.GameDealModel>>);

  @override
  _i3.Future<List<_i5.GameDealModel>> fetchDealsByTitle(String? title) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDealsByTitle,
          [title],
        ),
        returnValue:
            _i3.Future<List<_i5.GameDealModel>>.value(<_i5.GameDealModel>[]),
      ) as _i3.Future<List<_i5.GameDealModel>>);
}
